sonar.projectKey=nexacloud
sonar.projectName=NexaCloud
sonar.projectVersion=1.0

sonar.sources=services,frontend

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,\
**/.git/**,\
**/.scannerwork/**,\
**/dist/**,\
**/build/**,\
**/*.min.js,\
**/*.css,\
**/__pycache__/**,\
**/*.pyc,\
**/venv/**,\
**/migrations/**
